### ISSUE TITLE
Bug fixes for breakpoint envelope needed

### ISSUE THREAD

**Issue by elanhickler** [RobinSchmidt/RS-MET#99]
1. Setting a time value via slider does not update the ***view*** of the envelope, so, let's say you set time to 30 seconds via slider, you can't actually see that point, you can't zoom out because the "total length" that you are allowed see is still based on the previous time values. This is also true for setting level.

FIX: Send a notification when you change point time/level via slider just as you would when manually moving a point.

2. The default inserted point is currently stairstep... this caused some assertion errors in debug mode and possible line drawing errors because stairstep doesn't have a curve value therefore curve is 0, and if you switch the stairstep to something that ***does*** have a curve, then you get a default curve value of 0, for example, analog shape, which causes issues.

FIX: Make the default point shape analog (stairstep as default doesn't make sense!), and make sure your curve value is set when switching from stairstep to something else.

**Comment by RobinSchmidt** [comment]
uuuhh...stairstep for new breakpoints? i must have broken something when i fixed a bug related to not correctly recalling stairstep settings. actually, the idea is, that a new breakpoint get the same shape as its neighbour (and that was the behavior before, if i'm not mistaken). that makes most sense to me. sometimes you may want stairsteps, for example when setting up a step-sequencer like pattern ...i need to look into what i have broken

**Comment by elanhickler** [comment]
omg robin you forgot the most obvious feature for your breakpoint envelope!

You forgot to have "12" as one of your vertical divisions. This will allow you, with stairstep shapes, to create a nice little arp/melody. I would add in 12/24/36 for good measure. 😉

**Comment by RobinSchmidt** [comment]
that is because i have so far never used it to control the pitch but rather the frequency. the 12-tone division doens't make sense, when directly let it (multiplicatively) affect a frequency (which is what i do with the "pitch-env" in starightliner - which should perhaps more properly be called freq-env). but you can do melody sequencing in some kinds of just-intonation, you have pure octaves (2), fifth (1.5) minor and major thirds (1.2 and 1.25...i think? maybe wrong).

hmm...but within the new mod-system, it's certainly not unlikely that someone routes it to some kind of "tune" parameter...but maybe that will be scaled in semitones anyway, so the integers are actually appropriate. hmm...dunno

**Comment by RobinSchmidt** [comment]
or wait - you mean, major divisions every 12, and minor divisions at integers?

**Comment by RobinSchmidt** [comment]
i have restored the old behavior where new breakpoints copy their (right) neighbour settings. it got indeed broken when fixing this other bug - i even had comments in the code about this (they and the old and older code are still there for reference, but may eventually be deleted). will look into auto-updating the view now

**Comment by RobinSchmidt** [comment]
i'm updating the scrollbars now when you change a breakpoint time/level

**Comment by elanhickler** [comment]
ohh... hmm yes i guess you could zoom out vertically to see a height of 12 instead of dividing your 0 to 1 in 12.

**Comment by RobinSchmidt** [comment]
> you forgot to include vertical division quantizing for values of integers! 

what do you mean? it can vertically quantize on integers

**Comment by elanhickler** [comment]
yes now it can, but I don't care about that anymore, because it's easier to do melody sequencing with 1/12 division. Zooming out that far is not easy with your GUI.

**Comment by elanhickler** [comment]
CLOSED

**Comment by RobinSchmidt** [comment]
it just occurred to me that a user may want to sequence triplets, so 1/3, 1/6, etc should be available as well (at least for the x-axis). i'm slowly but surely beginning to think, it might be better, to let the user select numerator and denominator separately. ...or even just provide number entry fields for arbitrary, possibly irrational, divisions. hmmm

**Comment by elanhickler** [comment]
haha yes, a number entry would be welcomed.

We eventually need a dedicated arp sequencer and/or bar sequencer, or you can make your breakpoint EG more advanced to support more bar sequence style like KarmaFX. If you want to support arp 

see gif: https://puu.sh/y3Cnd/874db9ee11.gif
